name: Pull Request Opened Notification

on:
  pull_request:
    types:
      - opened
      - reopened

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
  PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
  PULL_REQUEST_AUTHOR_NAME: ${{ github.event.pull_request.user.login }}
  PULL_REQUEST_AUTHOR_ICON_URL: ${{ github.event.pull_request.user.avatar_url }}
  PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
  PULL_REQUEST_BODY: -----------------------

  PULL_REQUEST_COMPARE_BRANCH_OWNER: ${{ github.event.pull_request.head.repo.owner.login }}
  PULL_REQUEST_COMPARE_BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
  PULL_REQUEST_BASE_BRANCH_OWNER: ${{ github.event.pull_request.base.repo.owner.login }}
  PULL_REQUEST_BASE_BRANCH_NAME: ${{ github.event.pull_request.base.ref }}

  IS_SEND_HERE_MENTION: "false"
  SEND_USER_ID_MENTIONS: ""
  MAKE_PRETTY: "false"
  MAKE_COMPACT: "false"
  IS_PR_FROM_FORK: ${{ github.event.pull_request.head.repo.fork }}

jobs:
  check-labels-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Resolve Slack Mentions
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        env:
          SLACK_USERS: ${{ secrets.SLACK_USERS }}
        with:
          script: |
            const slackUsers = JSON.parse(process.env.SLACK_USERS);
            const labels = context.payload.pull_request.labels.map(label => label.name);

            console.log({ labels, slackUsers });

            if (labels.length === 0) {
              core.setFailed(
                "No labels found in PR.\n" +
                "Please add labels and reopen (or rerun) this workflow."
              );
              return;
            }

            const mentions = labels
              .map(label => slackUsers[label])
              .filter(Boolean);

            console.log({ mentions });

            if (mentions.length > 0) {
              core.exportVariable(
                "SEND_USER_ID_MENTIONS",
                mentions.join(",")
              );
            } else {
              core.exportVariable(
                "IS_SEND_HERE_MENTION",
                "true"
              );
            }

      - name: Send Slack Notification
        uses: jun3453/slack-pr-open-notification-action@fe4a6be204730358ffdecb4fc52405f4e67a371d # v1.3.0
