name: Workflow A

on:
  workflow_call:
    secrets:
      FAKE_TOKEN:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: TESTING
        run: |
          echo "FAKE_TOKEN=${{ secrets.FAKE_TOKEN }}"
          