name: Workflow A

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      FAKE_TOKEN:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-cache
      - name: TESTING
        run: |
          echo "TESTING"
          echo "FAKE_TOKEN=${{ secrets.FAKE_TOKEN }}"
