name: Workflow A

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      FAKE_TOKEN:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 24
      - name: Cache dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: ~/.npm
          key: npm-cache
      - name: TESTING
        run: |
          echo "TESTING"
          echo "FAKE_TOKEN=${{ secrets.FAKE_TOKEN }}"
